Use reusable actions in CI
SkynetLabs/nodejs-skynet pull request #138
Opened 2022-04-29 21:21 UTC by m-cat

# PULL REQUEST

## Overview

Use https://github.com/SkynetLabs/.github/pull/15. Has been tested in the `skynet-mysky` and `skynet-mysky-utils` repos.

2022-05-02 07:13 UTC, peterjan submitted a review, later dismissed

2022-05-02 09:00 UTC, ro-tex submitted a review, later dismissed

2022-05-02 14:41 UTC, MSevey requested changes

2022-05-02 14:41 UTC, MSevey commented on .github/workflows/ci.yml
> +    branches: [main]
this repo's branch name is `master`

2022-05-02 14:49 UTC, m-cat commented on .github/workflows/ci.yml
> +    branches: [main]
Good catch. 😬

2022-05-02 19:25 UTC, MSevey approved these changes

2022-05-03 08:35 UTC, ro-tex approved these changes

2022-05-03 08:35 UTC, merged